language: c++

matrix:
  fast_finish: true
  include:

  - dist: focal
    compiler: gcc
    addons:
      apt:
        packages:
          - python3-pip
          - python3-setuptools
    env:
      idx=1
      N=Focal
    install:
      # install required python packages
      - python3 -m pip install sklearn xgboost pandas numpy
    script: 
      - cd ${TRAVIS_BUILD_DIR}
      - ln -s $PWD/benchmark/xgboost2tmva.py $PWD/test/xgboost2tmva.py
      - cd test && python3 create_test_data.py && cd ..
      - mkdir build
      - cd build
      - cmake -DEXPERIMENTAL_TMVA_SUPPORT:bool=true ..
      - make
      - sudo make install
      - cd ../test
      - ../build/test/Test

  - dist: bionic
    compiler: gcc
    env:
      idx=2
      N=Bionic
    script: 
      - cd ${TRAVIS_BUILD_DIR}
      - mkdir build
      - cd build
      - cmake -DEXPERIMENTAL_TMVA_SUPPORT:bool=true ..
      - make

  - dist: xenial
    compiler: gcc
    env:
      idx=3
      N=Xenial
    script: 
      - cd ${TRAVIS_BUILD_DIR}
      - mkdir build
      - cd build
      - cmake -DEXPERIMENTAL_TMVA_SUPPORT:bool=true ..
      - make

  - dist: trusty
    compiler: gcc
    env:
      idx=4
      N=Trusty
    script: 
      - cd ${TRAVIS_BUILD_DIR}
      - mkdir build
      - cd build
      - cmake -DEXPERIMENTAL_TMVA_SUPPORT:bool=true ..
      - make
